### ISSUE TITLE
Example with a dedicated REST Edge Server 

### ISSUE THREAD

**Issue by sherifkayad** [featurehub-io/featurehub-examples#49]
Hi, I have a really strange issue at the moment. With a party server (e.g. running in Docker with Docker Compose) and using the Spring Boot sample, all works great. Once I try to run with a separate MR and REST Edge server (e.g. https://github.com/featurehub-io/featurehub-install/blob/main/docker-compose-options/mr-edge-rest-postgres/docker-compose.yaml), then the client doesn't work anymore and the `featureHubConfig.init()` blocks indefinitely.

Having a look at the logs of the Edge server, one could see tons of 404s.

My Code:
```java
@Bean
    public ClientContext featureHubClientContext() {
        final FeatureHubConfig featureHubConfig = new EdgeFeatureHubConfig("http://localhost:8553",
                "cb1d9cee-4443-4c99-afea-128889cea7f9/IqbpVJeZ20rYoqHpst31xhFjw2JGXZ*79hA4HAYBiImNKkmxqdO");
        // featureHubConfig.init();
        LOGGER.info("FULL URL :: {}", featureHubConfig.getRealtimeUrl());
        LOGGER.info("STATE OF THE FH CONFIG :: {}", featureHubConfig.getReadyness());
        return featureHubConfig.newContext();
    }
```

**Comment by rvowles** [comment]
Hi there! You are  using a streaming  config  with EdgeREST and it doesn't support it, it only  supports REST  calls, not  SSE calls as it has no pub/sub  infrastructure.... Party Server  has NATs bundled into  the image which is why its working.

Hope that helps?

**Comment by sherifkayad** [comment]
@rvowles that explains a lot of things thanks so much. Can you point me in the easiest right direction for a GET client potentially with Polling like with the frontend such that I can invoke Featurehub over REST from a boot app?

**Comment by rvowles** [comment]
If you swap out the jersey  dependency with java-client-android  and then create a Spring (or just  a  Timer really)  that calls config.getEdgeService().get().poll();  inside  it, that will cause the  polling to happen automatically.

**Comment by sherifkayad** [comment]
Thanks a lot for that. Let me try this tomorrow first thing and get back to you. Much appreciated 😌

**Comment by sherifkayad** [comment]
Works like a charm! thanks a lot!
